### ISSUE TITLE
SVN 2 TFS or SVN to GIT to TFS?

### ISSUE THREAD

**Issue by clockwiseq** [spraints/svn2tfs#1]
Hello, I have used your utility in the past to convert from svn to tfs, but ran into various issues that I do not currently recall, but since it was so long ago that I attempted it, I was wondering if there was a better roadmap now?  Instead of going directly from svn to tfs, should I first do a pull from svn into a local git repo and then push to tfs or use this utility?

**Comment by spraints** [comment]
This repo is a fork of the [svn2tfs project on codeplex](https://svn2tfs.codeplex.com/). I don't have plans to do anything with this, so you'd probably be better off asking over there, though it doesn't look like there's much activity.
